### ISSUE TITLE
duda selectores

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#10]
Buenas tardes @pedroprieto tengo una duda en el ejercicio de formularios ya lo tenia bien pero tenia el inconveniente de que tenia como selector querySelector("form") y en la siguiente practica al ingresar un form nuevo dio error la practica anterior.

Ahora he intentado seleccionar el form del template según lo indicas y no lo selecciona, lo he intentado de varias formas y no lo he logrado no se por que el template al mirar el dom en consola me aparece sin hijos como un elemento vacío.

en gestionPresupuestoWeb.js he intentado hacerlo de todas las formas posibles( de la linea 316 a la 325) y nada aun, para que me pasara el test le agregue un id mientras me corriges el fallo.

gracias.

**Comment by pedroprieto** [comment]
Buenas,

El problema es que esta línea:
https://github.com/Ivancamviv/practica_dwec_gestor_presupuesto/blob/fa4d816a55c72013a204fda9f1cbd65a5ea4491f/js/gestionPresupuestoWeb.js#L314

Debe ir después de interactuar con el fragmento. Debes añadirla al final, cuando termines de hacer todo, tal como indica el enunciado. Después de:
https://github.com/Ivancamviv/practica_dwec_gestor_presupuesto/blob/fa4d816a55c72013a204fda9f1cbd65a5ea4491f/js/gestionPresupuestoWeb.js#L334

Si añades el fragmento al HTML mediante `append` dejas de poder interactuar con él y se transforma en un objeto del DOM más.

Un saludo!!
