### ISSUE TITLE
duda api

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#11]
Buenas tardes @pedroprieto tengo una duda al buscar en la api por el id del gasto creado tocaria llamar a anyadirGasto para asignarle el id al objeto gasto creado pero este le asigna un valor segun el contador en este caso(6) veo que al buscar en la api con ese id no funciona por ejemplo en tu propia prueba de la api  https://suhhtqjccd.execute-api.eu-west-1.amazonaws.com/latest/pedroprieto/0 donde 0 seria el id del gasto, pero como puedes ver ese id no existe.

https://suhhtqjccd.execute-api.eu-west-1.amazonaws.com/latest/pedroprieto/cf762a1f-44da-47cc-aba3-9264b1bc2522 este si existe pero veo que el id se lo asigna la api automaticamente  en gastoId. Debemos con fetch llegar al gastoId de para poder borrarlo o es un fallo en la api?

**Comment by pedroprieto** [comment]
Buenas,

Estas dudas puedes ponerlas en el foro mejor. Así le sirve a todo el mundo.

La API es independiente de los gastos locales creados al principio. Lógicamente en una aplicación real solo trabajaríamos con la API.

Debes trabajar con los gastos que crees y leas en la API, ignorando los gastos locales que creamos al principio.

Un saludo!
