### ISSUE TITLE
Duda sobre objetos 

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#3]
Buenas profesor @pedroprieto tengo este codigo en crearGasto y en el objeto gastos

`function CrearGasto(descripcion,valor) {
    // TODO
    this.descripcion = descripcion;
    if(valor >= 0 && typeof valor === 'number' ){
        this.valor = valor;
    }
    else{
        this.valor = 0;
    }
    
}

let gastos = {
    descripcion : " ",
    valor: 0,

    mostrarGasto(){
        alert(`Gasto correspondiente a ${descripcion} con valor ${valor} €`)  
      },

      actualizarDescripcion(nuevaDescripcion){
        this.descripcion = nuevaDescripcion;
      },

      actualizarValor(nuevoValor){
          if(nuevoValor>0)
          {
            this.valor = nuevoValor;
          }
        
      }

};`

tengo un par de dudas como hacer que el constructor devuelva un objeto gastos?? y como desde el constructor se puede ingresar a los metodos de gastos??; Osea al crear un nuevo objeto con el constructor CrearGasto() como puedo ingresar a esos metodos de gastos?

**Comment by pedroprieto** [comment]
Buenas,

Te he comentado en la PR. Supongo que te refieres a lo que te he comentado sobre el código que te sobra. Efectivamente, está duplicado.

Un saludo!
