### ISSUE TITLE
pasar las etiquetas separada

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#7]
Buenas tardes profesor @pedroprieto tengo una duda en la parte del ejercicio donde dice ¡Ojo con la manera de pasar el parámetro ~etiquetas~! en la funcion nuevoGastoWeb he estado probando con for..of  para pasar los elementos del array 1 a 1 pero no funciona

**Comment by pedroprieto** [comment]
Buenas,

El tema es que vas a recoger las etiquetas en un array: sin embargo, la función `crearGasto` admite las etiquetas como una lista de parámetros, no como un array. Por tanto, tienes que convertir el array de etiquetas a una lista de parámetros. Pista: https://es.javascript.info/rest-parameters-spread

Ánimo!!

**Comment by Ivancamviv** [comment]
Buenas profesor @pedroprieto, tengo un  pequeño lio por que no encuentro el por que al darle al boton de editar me repite la funcion editarHandle 6 veces.
he relaizado los cambios con el spread y va bien pero no logro asignar la funcionalidad de cada handler a su respectivo gasto.

el llamado del objeto esta en gestionpresupuestoWeb entre la linea 61-70 y la funcion editarHandle en el mismo archivo en la linea de 177-196

**Comment by pedroprieto** [comment]
Buenas,

El problema está aquí:
https://github.com/Ivancamviv/practica_dwec_gestor_presupuesto/blob/31f9f7d7c4d0c6c50254466d351db75adf6d3a52/js/gestionPresupuestoWeb.js#L66
https://github.com/Ivancamviv/practica_dwec_gestor_presupuesto/blob/31f9f7d7c4d0c6c50254466d351db75adf6d3a52/js/gestionPresupuestoWeb.js#L67

No tienes que hacer ese bucle. `mostrarGastoWeb` pinta un único gasto. Por tanto, no tienes que buscar todos los botones.

Tienes la referencia al botón que necesitas en esta variable:
https://github.com/Ivancamviv/practica_dwec_gestor_presupuesto/blob/31f9f7d7c4d0c6c50254466d351db75adf6d3a52/js/gestionPresupuestoWeb.js#L55

Por tanto, es tan sencillo como hacer `button.addEventListener('click',nuevoObj);`

Un saludo!!

**Comment by Ivancamviv** [comment]
vale lo entiendo no le paso la referencia de la clase si no desde el mismo botón creo que addEventListener, es que claro el for era por que haciendo pruebas veía que si uso el getElementsByClassName tengo q recorrerlo como una array para usar el addEventListener.
