### ISSUE TITLE
duda formulario de las etiquetas

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#8]
Buenas tarde profesor @pedroprieto tengo una duda en la ultima parte del ejercicio que es editar los gastos con el formulario toca realizar un formulario o se usa el template?

desde el EditarhandleFormulario se puede acceder al template?

**Comment by pedroprieto** [comment]
Claro, debes utilizar el `template` también. Y sí, puedes acceder al `template` de la misma manera que en la función `nuevoGastoWebFormulario`.

Un saludo!
