### ISSUE TITLE
correcion de la practica eventos y terminacion practica formularios

### ISSUE THREAD

**Issue by Ivancamviv** [Ivancamviv/practica_dwec_gestor_presupuesto#9]
Buenas noches profesor @pedroprieto he terminado la practica de esta semana y he corregido el fallo de la anterior no se si tengo que hacer pull request por que en un mensaje anterior me informo que deja la pull request anterior abierta.

**Comment by pedroprieto** [comment]
Buenas. Sí, he visto los cambios. Voy a corregirlos. Gracias!

**Comment by Ivancamviv** [comment]
Buenas profesor @pedroprieto tengo una duda que me gustaria que me ayudaras, en la mejora del codigo de la funcion filtrarGastos lo he realizado como nos explicaste pero no me pasa el test y veo que para las expresiones regulares necesito de esta funcion.

te agrego el codigo de la funcion

`function filtrarGastos(objeto){

let nuevaMatriz = gastos.filter(filtro =>{
 
 
  
  let result = true;
  
  if (Date.parse(objeto.fechaDesde) > filtro.fecha){
   
   result = false;
  
  }
  
  if (Date.parse(objeto.fechaHasta) < filtro.fecha){
   
    result = false;
  
  }
  
  if (objeto.valorMinimo > filtro.valor){
   
    result = false;
  
  }
  
  if (objeto.valorMaximo < filtro.valor){
   
    result = false;
  
  }
  
  
  if ( objeto.descripcionContiene === undefined){
  
   	  result = true;
   
  }else if(filtro.descripcion.indexOf(objeto.descripcionContiene) == -1){
  
 	  result = false;
      
  }
  
 
 if ( objeto.etiquetasTiene === undefined){
  
   	 result = true;
    
   
  }else{
  	
 	 for (let x of objeto.etiquetasTiene) {
   		
       		 
            
            if (filtro.etiquetas.indexOf(x) != -1) {
          		  
         		  result = false;
               }
          
  	  }
      
     
     
  }
 
  return result;
});

return nuevaMatriz;
}`

**Comment by pedroprieto** [comment]
No te ha cogido bien el formato. Para código multilínea utiliza tres acentos:
````markdown
```js

código

```
````
Hazlo así y lo estudio.

Un saludo!

**Comment by Ivancamviv** [comment]
vale, muchas gracias.
``` js
`function filtrarGastos(objeto){

let nuevaMatriz = gastos.filter(filtro =>{

let result = true;

if (Date.parse(objeto.fechaDesde) > filtro.fecha){

result = false;

}

if (Date.parse(objeto.fechaHasta) < filtro.fecha){

result = false;
}

if (objeto.valorMinimo > filtro.valor){

result = false;
}

if (objeto.valorMaximo < filtro.valor){

result = false;
}

if ( objeto.descripcionContiene === undefined){

  result = true;
}else if(filtro.descripcion.indexOf(objeto.descripcionContiene) == -1){

  result = false;
}

if ( objeto.etiquetasTiene === undefined){

 result = true;
}else{

 for (let x of objeto.etiquetasTiene) {
	
   		 
        
        if (filtro.etiquetas.indexOf(x) != -1) {
      		  
     		  result = false;
           }
      
  }
}

return result;
});

return nuevaMatriz;
} ```

**Comment by pedroprieto** [comment]
Creo que el problema está en `objeto.fechaHasta` y `objeto.fechaDesde`. Tal como pone el enunciado, son strings con formato de fecha. Por tanto, antes de comparar tienes que convertir a timestamp con `Date.parse`.

Un saludo!
